* Learning Outcomes
*Desired Outcome*:

I want to learn what a small business can otter when comparing services that large cooperation currently offer. Are SMB's more or less flexible.

*How*:

While working I will take note oi different services that this company can offer regarding their flexibility and willingness to work tor the customers needs. I will then compare these capabilities with their large competitors.

*Measurement*:

The measurement of objective will be measured by using survey tables of services offered. By using this method I strongly feel that we will be able to show that the SMB has probable cause showing they are still viable when faced with large business competition.

*Desired Outcome*:

I want to learn how to Market a SMB with the limited budget that SMBs normally undergo.

*How*:

Currently I have limited knowledge of how to market. My experience with the subject is only with companies that have entire departments devoted to the subject. SMB's need to be more creative with getting their out into the world. I will undergo different learning from using social media then explore more traditional options.

*Measurement*:

To measure this I will use the simple test showing that I have learned different ways by actually creating some form of marketing material for the company.

*Desired Outcome*:

I want to learn the daily operations of Old West Escrow. This company is unique in the sense that they are not a mortgage convay or own any of the loans they service. The company acts as a neutral third party to private lenders and borrowers. I feel that sets up a unique work environment that takes skill when working with both parties involved in transactions.

*How*:

I will accomplish this by accepting the job as an account manager. The job position will place me in the middle of the daily process of accounts learning how to calculate different interest rates as well as learn the different aspects of the real estate market.

*Measurement*:

This goal is measured by my supervisor. They will perform an evaluation of my work checking for work accuracy and general knowledge of performing the job duties.

*Desired Outcome*:

The Small Business owner has many tasks that they are responsible for. This creates multiple instances where they are not only worrying about the products they sell their customers but they have to think accounting, marketing, and hiring decisions My goal is to observe how these tasks are carried
out and how to manage all the aspects that are required when having multiple departments for these
tasks are not feasible.

*How*:

I will observe these activities and perform the functions as needed by the business. During these observations will record the actual process then determine if there are better to the problem.

*Measurement*:

This outcome will be measured by performing the actual task that is required. If areas can be improved
upon the options will be discussed with the supervisor on how to implement a new process. I want to
know how many hours of work it takes to perform these specific functions.

*Desired Outcomes*:

I want to learn how to apply my business teachings to solve applied problems

*How*:

I will keep a log of my workdays while performing my internship. When applied problems are I will document what actions I used to solve the problem documenting what I learned from the situation and
how it was solved.

*Measurement*:

The measurement of this objective is based on a critique of the outcome of the solution and whether the solution I supplied was used or not.

*Desired Outcome*:

I want to demonstrate leadership behaviors such as initiative, focus and high performance standards

*How*:

I will achieve this outcome by setting high standards for myself by constantly evaluating the quality of my work. I will also follow all projects and work related tasks to their completion demonstrating my focus and initiative as a professional.

*Measurement*:

The measurement of this outcome will cone as a critique of both my strengths and weaknesses coupled with a solicited survey reflecting how my initiative and focus were perceived.
* Reflection of Internship
* Resume
* Journal Entries
** January 11-17


Job Description

Account Manager

My job at Old West Escrow is to record numerical data to keep financial records complete. This is done by performing any combination of routine calculating, posting and verifying duties to obtain primary financial data for the use to administer privately funded contracts. The job also requires the accuracy of figures, calculations, and postings pertaining to business transactions recorded by other workers. 

** January 18-24

My Organization is for this internship is Old West Escrow Company Inc. They are located at 2800 Jackson blvd in Rapid City South Dakota. This organization is very small and I would classify it as a micro business. There are not vary many employees considering that it doesn't take much work to complete the job. At this point in time the organization consists of the CEO/ Owner and one other employee. 

** January 25-30
				   
The effective and ineffective communications at this intern site are many. I feel the ineffective communication stems from generational gaps. The effective communication is awesome. The employees communicate with the owner freely and openly and the owner clearly verbally communicates with her employees asking for clarification when needed. The ineffective communication comes when technology is involved. The owner doesn't understand the use of email and will only use a fax machine when communicating with outside companies. On the other hand the other employee uses email to do this communicating. This prove to be vary ineffecient because depending on who answers the phone calls during the day coraspondance is performed differently with the outside companies. If for instance a customer only has email and does not have access to a fax machine that customer then has to wait until the other employee sends the email. Sometimes because of this disconjointed system communication gets lost between the two and the tasking gets lost. I feel that this is unfortanent because this might send a message that Old West Escrow is disorganized. 

The internal effective communication is great between the owner and the employees. Both parties are equally open and willing to communicate about future offerings as well working together to solve problems that arise from the daily work. One such incident where I noticed this was when there was a disagreement about how to apply a late charge on the account. The contract states to apply the late fees on a per day basis. The conflict happened when they made a payment and enoumous late fees kicked in. Both the owner and the employee were right on their thinking and instead of getting mad at each other they worked the problem out with math to make their case. There was collaboration between the two until they figured out the problem. I really liked this aspect because I have worked in so many organizations where employees thought and ideas don't ever seem to matter to the ones in charge. In the case of this organization both the employee and the management work together in a seamless environment making a frictionless environment. 

** February 1-7

Within the organization there is a divide in reguards to the technology that is used. When I arrived at the organization they were still using a dos made program that hasn't been updated since the mid 1990's. As we might guess this program has limitations when working in the technology driven world that we live in today. As mentioned earlier not all the employees work from email. The owner of the company doesn't ever want to use email for external communications while the rest of the world uses exactly that technology for those tasks.

In today's customer marketplace customers demand that everything they do to be connected by their fingertips. In my expirence when a customer is doing finicial transactions they want to be able to see those transactions when they want to. They don't want to call the company for every question they have. This is where using technology that was built for pre-internet doesn't work that well with maintaining customer relationships.

The main recomandation I have for this organization is to have all employees using the same technologies across the board. Having one person using aniquated technology only while the other is keeping more modern using email with attachments cause confusion between employees. This confusion then enables the organization to deliver delayed results because one maybe relying on the other to complete tasks. Personally I would like to see all employees embrace electronic communications in the future. The next item is the use of the software package that the company is using. With the software created in the mid-1990's there seems to be a lot that is left to be desired. When looking further into the type of software they use I found that there are in fact newer versions available that offer all the features that customers look for when dealing with financial transactions. I would recommend that the company undergo the software conversion process in order to take advantage possible gained competitive edge. 

** February 8-14

This internship is meeting all of my expectations thus far. When I picked this internship I wanted to better understand the challenges of running a small business. This organization is a small business with vary few employees. These types of businesses have their own set of challenges that the large companies don't seem to have or are easy hurdles to cross. I have worked at a number of large to mid-sized organizations and know the different red tapes they have to jump thorough. I have never been at such a company where budgets, human resources, capital huge restraints. Within these types of companies often times human resources and budgets go hand in hand. The organization truly needs more of the aforementioned ,however, the constraint mechnisums are such that without one the other cannot be performed. 

When looking at other companies that offer the same services this company would be classified as a mid-sized company. There are so few employees because it does not take an army of human resources to accomplish the daily work. It does however, need human capital that is highly versed in different aspects business management. What this means is that one person is responsible for the marketing, payroll, budgeting, and financial bookkeeping.  

** February 15-21

Since I chose to use an small business as my choice for my internship I feel that I am adaquately able to use most of the classroom learning from my undergraduate degree as well as my last three years with Chadron State University. So far I have been using areas from my marketing, public relations, accounting, math for managers etc. I feel that this is the most rounded expirence I could have come across. Throughout my time in this internship I am not just an inicent bystander during the process of the work week. My intern site has me working though the everyday problems and working directly with the customers. This site also values my input on best practices when looking at new competitive advantages. I am truly happy that during this adventure I have been able to use and practice all classroom teachings and apply them to real world examples. 

** February 22-29

There are many area's of this internship that I would like to share with my classmates that relates to to our classroom learning. The first expirance that I learned really quick was that during the internship when looking at market factors and finding the equalibriam it is not that simple. Finding what consumers are willing to pay verses their reactions to pricing seems to be more difficult to acheive. An example of this is when visiting with the company about new possible revenue streams on paper they seemed easy enough to accomplish. In practice when quoting the new different pricing the reactions varied greatly, sometimes over the smallest change that resulted in an extra dollar. At the same time when changing the pricing internally without a public notice the results seemed to be better taken of the consumer didn't know the price before hand. An example of this practice what changing the pricing of closing costs. Before the change the company was charging a flat rate for all closing but added on extra fees depending on how many payoff quotes had been requested. The new pricing changed out that variable and went with a flat fee plus a percentage cost basis. In this case consumers didn't think twice about the price charged. The origional way consumers would cry foul when tacking on extra fees because a external company requested payoff quotations at different times throughout the contrat to varify their credit worthiness. 

This example shows that finding the equalibrium in the market isn't simply the result of consumer surveys binded with the cost of goods or servies. Consumers are much more dynamic that this which can result in knee jerk reations. Though consumer surveying has it's place in our current market other external factors needs to take place to trulely find that market balance. 

** March 1-6

I have rather large long and short term career goals. Currently my short term career goals consists asking the question to myself of what can I do to make my job and internship better. Everyday I want to better the business that I work in. So my current short term goals consist of finding areas that needs improvment and finding ways to simplify the process that make work easier with the same amount of control and accracy as the current process. Currently I am working on a project to increase my companies revenue without raising costs. I am accomplishing this by sorting out unneeded expenses or expenses that are redundent. One area that I found was by chance. I was given the task of calling the phone company to order a new modem. This call resulted in learning that the comapany had not updated their service package since the year 2000. By ordering a new modem the company was switched to new updated packages that saved one hundred and thirty six dollars a month. This set me off to find other areas of similar interest. Another goal is to find ways to reduce the company's cost of postage. This is by far their largest expense for the year. Currently there are several options available to the company but the new processes also require an initial cost of entry before savings can happen. These short term goals are very short term but I choose these goals as my short term because they demonstrate the ability to problem solve. This is an important ablitiy that rolls into my larger long term goal.

My Long term goal is to own my own business. This is one reason that I chose a micro business as my intern site. If I would have chose a site where I was bounded to a certain department burried deep within a corperation I feel that would give me a vary narrow view of what the larger picture is. By choosing this type of site in a short time I am able to view the entire picture of what is needed when we look at professional and personnal skills.  In a the short time that I have had I have already learned that a SMB needs to have a well rounded understanding of all things business. They are the marketer, human resources, and accounting. Running this type is business is a trial and error process in many way. The process is also a never ending learning expirance. Of course the business can hire professional services to fill many of the gaps that exist, however, there is always the issue of cash flow that plagues each and every one of these companies. So by having this internship site I feel that I will be better poised to understand if my long term goals are attainable. 

** March 7-13



** March 14-20

** March 21-27

** March 28-30

** April 4-10
* Thank You Letter
this is for real now
