* Learning Outcomes
*Desired Outcome*:

I want to learn what a small business can otter when comparing services that large cooperation currently offer. Are SMB's more or less flexible.

*How*:

While working I will take note oi different services that this company can offer regarding their flexibility and willingness to work tor the customers needs. I will then compare these capabilities with their large competitors.

*Measurement*:

The measurement of objective will be measured by using survey tables of services offered. By using this method I strongly feel that we will be able to show that the SMB has probable cause showing they are still viable when faced with large business competition.

*Desired Outcome*:

I want to learn how to Market a SMB with the limited budget that SMBs normally undergo.

*How*:

Currently I have limited knowledge of how to market. My experience with the subject is only with companies that have entire departments devoted to the subject. SMB's need to be more creative with getting their out into the world. I will undergo different learning from using social media then explore more traditional options.

*Measurement*:

To measure this I will use the simple test showing that I have learned different ways by actually creating some form of marketing material for the company.

*Desired Outcome*:

I want to learn the daily operations of Old West Escrow. This company is unique in the sense that they are not a mortgage convay or own any of the loans they service. The company acts as a neutral third party to private lenders and borrowers. I feel that sets up a unique work environment that takes skill when working with both parties involved in transactions.

*How*:

I will accomplish this by accepting the job as an account manager. The job position will place me in the middle of the daily process of accounts learning how to calculate different interest rates as well as learn the different aspects of the real estate market.

*Measurement*:

This goal is measured by my supervisor. They will perform an evaluation of my work checking for work accuracy and general knowledge of performing the job duties.

*Desired Outcome*:

The Small Business owner has many tasks that they are responsible for. This creates multiple instances where they are not only worrying about the products they sell their customers but they have to think accounting, marketing, and hiring decisions My goal is to observe how these tasks are carried
out and how to manage all the aspects that are required when having multiple departments for these
tasks are not feasible.

*How*:

I will observe these activities and perform the functions as needed by the business. During these observations will record the actual process then determine if there are better to the problem.

*Measurement*:

This outcome will be measured by performing the actual task that is required. If areas can be improved
upon the options will be discussed with the supervisor on how to implement a new process. I want to
know how many hours of work it takes to perform these specific functions.

*Desired Outcomes*:

I want to learn how to apply my business teachings to solve applied problems

*How*:

I will keep a log of my workdays while performing my internship. When applied problems are I will document what actions I used to solve the problem documenting what I learned from the situation and
how it was solved.

*Measurement*:

The measurement of this objective is based on a critique of the outcome of the solution and whether the solution I supplied was used or not.

*Desired Outcome*:

I want to demonstrate leadership behaviors such as initiative, focus and high performance standards

*How*:

I will achieve this outcome by setting high standards for myself by constantly evaluating the quality of my work. I will also follow all projects and work related tasks to their completion demonstrating my focus and initiative as a professional.

*Measurement*:

The measurement of this outcome will cone as a critique of both my strengths and weaknesses coupled with a solicited survey reflecting how my initiative and focus were perceived.
* Reflection of Internship
** Introduction
I am currently seeking graduate studies of organizational management. I chose this instead of pursuing a master's of business administration because I have always felt that the success of a company resides soley in the hands of the people they hire. After that the financials will fall into place. The second reason was because I have spent many years in organiztaions where the management was really needing work with treating their employees. Having worked for one of the best in this respect, I learned a great deal of what it means to take care of the employees and the employees will take care of you. This leads to why I chose an organization to intern with that didn't have many employees. I wanted to see this dynamic. I wanted to witness first hand how an organization that was completly flat with it structure performed and I wanted to learn how small businesses fill the voids that large comapnies leave in the market. 

Choosing an internship site for myself was a difficult process. What I really wanted was to embark on a aspect of the workforce that I have not yet performed. I had several options available to me. The option that I almost pursued was to intern with a prior employer but studing under the General Manager. I decided against this avanue because I felt that I had alreay expiranced almost everything that is available in that office. What I am really interested in is not how to be in a managerial position but instead wanted the entire business expirance at once.

Old West Escrow Company offered more than just an observational expirance. This was a fully immersive undertaking that so far proved to be one of the best decisions that I have made. I felt I needed a postion that allowed me to fully utilize the teachings from the past three years hopefully contributing to a company for furture success. So far I feel that I have accomplished this underlining goal and commitment to the company. I have complete projects ranging from developing a new website to simplifing daily processing reducing clerical errors resulting in an increase in productivity. 

** Introduction to Experience

When the time came to pick an organizaton to perform an internship with was a daunting task. I clearly know where I want to be in the future. For myself the future isn't the hopes of attaining large sums of money. Rather I want to work for myself. I want to go to work not because I have a boss that says I have to arrive at a certain time. I don't want to be in an environment that dictates that I grow a certain percentage every year. I understand that these grips are still needed when self employed, however, in corperate environments a persons worth to the company is based on such standards as percentage growth year over year. This leads me to the point where I decided to find a small company that had a flat organizational structure with low overhead. A company of this type was going to help with the logistics of be being self employed. 

During this internship I was inducted into the world of private financing. Private party finiancing is an activity where a potential borrower seeks out loans from a party other than a lending institiution such as a bank. This allows for the borrower to extablish a different line of credit than we are used to utilizing. The Job as an account manager allowed for the calulations relating to mortage and mortage interest. The job also dealt directly with the customers. I had to learn that no matter what in this business the customer is not always right allowing for the new knowledge of how to handle customers when it relates to finicial transactions. Performing the job as a account manager was just a small aspect of the entire internship expirance.

** Job relation to organizational functions

Old West Escrow uses the matrix structure for their organizational functions. Within the organization there is no seperate departments for each functions and there are no seperate divsions that have their own product lines or chain of authority. The employees in this organization have thier assigned tasks but are assigned other tasks depending on their stengths. For an example the owner is not well versed in marketing anymore so she would assign this to another employee to create good copies that would then be approved. This type of process happens for ever organizational functions within the company. 

My job as the account manager seemed at first to have a vary narrow scope. After performing the job for several weeks and the trust of the organiztion grew I was eventully assigned other functions to perform. In addition to the account manager I performed tasks related to the computer system or IT, budgeting, and marketing.

During my internship I performed many organizational functions. Two of the most notable was leading the company in a software conversion process to update from a software that was outdated and lacked any modern features that we would expect in the post internet world. The upgrade and conversion process involved the clean up and organization of the old system so when the outside company converted our database everything would be transfered correctly. On the back end of this process was the record keeping of all file changes that happened in the twenty one days from the time we handed the software off to recieving the new software package back. The next process was to re-enter each of those changes on the new software before the company could continue with normal daily operations. 

The next extra organizational function was more of a side project to work on in my free time. The company realized that the website was outdated and in need of some work. Albeit this project is not yet completed and I won't complete the project until after this internship. I have started work on the new website changing the look and feel of the site. This is a particularly tough task for the company. When they were looking at creating a new site they first went to outside companies looking for that help. They quickly realized that these options were outside their current budget and began looking internally for a person that was willing to write a site from the ground up. The problem was that every company that they called looking for price quotes quoted a price of $1,800 and up. This price was just for the creation of a simple site with up to ten pages. Then they were adding on an extra $1,200 for the inclusion of a web pay option or a authorize.net button. This was just too expensive for the company considering that these prices didn't mean the firms would create the site from scratch with custom designs. They would use a template. 

Over the course of this internship the narrow job title of account manager really only accounted for a small portion of the day. The rest of the time I spent performing other organizational functions that were needed as they arose. This was the benefit of doing the internship at a small company. I was able to broaden my work expirance to multiple areas of the organization. I feel that this process greatly started to prepare me for my personal long term goals. 

** Analysis and Evaluation
*** Observations and Thoughts
**** Learning Outcome One

Starting out in this internship I really had a hard time deciding on what learning outcomes I wanted from this expirence. My goals ended up focusing on how a business of this size is able to perform against large rivials in the industry. Though through research and visiting with the software company that provides software to such companies I learned that there are not many large companies that are competitors. Essensially I learned that in the early 1990's many banks decided that this type of business is not the right fit for them selling these accounts to other companies. In fact this is how this company started out. They bought accounts from banks that are no longer operating such as Norwest bank, Fidelity and many others. In the region this company operates there is still one large competitor which is First Interstate Bank. First Interstate Bank however, recently decided to reduce their offerings to only accepting accounts that are commercial accounts meaning non-owner occupied. By studing this market trend I see that small businesses are able to effectivly compete by filling the voids that are left when large organizations decide to leave a market. 

Looking at the first learning objective I set out to compare sevices that large cooperations currently offer deciding if small companies of this type are in fact more flexable and competitive in this market. After performing some research on a few companies in the region along wtih one company that is not in the current region I learned that Similar companies perform the same functions for thier customers. The difference was First Interstate Bank which recently pull out of the owner occupied mortage market. I found this interesting. I started thinking that a small company in this market was really filling a void left in the market. In reality they are not. The point being made though is that there is only one large corperation that is offering these sevices. The differences seemed to stem from the different price points between the compaines studied. The bank's start-up fees are based on the principal balance of the account $100 dollars for the first $50,000 then an additional $1.50 for each thousand after that. They also charge $10 for each check that is dispersed to the sellers of the accounts. In contrast the small business listed in table 1.1 all have similar start-up fee's. Old West Escrow for example uses a flat fee on $150 the same hold true for the other two companies listed, they are both using flat start-up fees and similar processing fees. 

When looking at the differences between these companies trying to draw a line that shows competitive advantage toward the small organizaiton seems difficult at first. This table is also defeating when we hoped to show that a large company would offer less services than the local organizations. I do not think though that compairing services between companies show the real advantages and disadvatages between the organizational sizes. Digging deeper we would find that as a customer if we were using First Interstate Bank our documents and paymenst are sent to Missoula Mt. taking away from the one advantage that customers want when they choose a local company. Looking upon the first learning objective I think that if we strip it down large organizations can indeed offer the same flexablity as the small business. This just looking at the list of services from various companies. However, when I started to search the the various fee schedules I found it apparent that fees really stack up quickly when the bank was compaired to the SMB. My thoughts involving the fees is that the bank has larger overhead when compairing the two resulting in the larger fees we see between them.  

| Table 1.1                | Old West Escrow | Black Hills Escrow | First Interstate Bank | INCS LLC       |
| Mortage Payments         | x               | x                  | x                     | x              |
| Safekeeping of documents | x               | x                  | x                     | x              |
| Trust funds              | x               | x                  | x                     | x              |
| Lease with Option        | x               | x                  | x                     | x              |
| Mergers/Buyouts          | x               | x                  | x                     | x              |
| Investments Offerings    | x               | x                  | x                     | x              |
| Settlement of Claims     | x               | x                  | x                     | x              |
| Owner Occupied Mortage   | x               | x                  |                       | x              |
| IRS Reporting            | x               | x                  | x                     | x              |

**** Learning Outcome Two

The biggest challenge to the small organization is how to market the company. This is a real delimia for all business owners. If the company doens't have the capital to invest in thier marketing plan how do they market to their segment to continue to stay in business. In the more recent years there has be a large influx in marketing in social media such as Facebook, LinkedIn, and Twitter. These sites offer low cost to entry and is really easy to select the demographics that a company is looking for. A prior organization I worked for switched to using these sites primarly for this purpose. Can a small local business use this same system to market themselves and acheive the same results? 

Currently at Old West Escrow the marketing plan is to advertise in the Yellow Pages also relying on word of mouth when securing new contracts. From my studies I feel that this is a passive way of advertising and the company needs to adopt an active approch to their marketing plan. The question remains, what forms of advertising will be the most effective. When researching the topic the first instinct is to use Facebook to promote the SMB in fact this has been encouraged by Facebook. Searching for this answer &fast company& published an article pointing out that in 2012 posts that businesses published on Facebook only reached 16% of thier target audience. Since that publication Facebook started offering promoted posts to target the low organic reach. By 2013 500,000 company pages used their promoted posts, however, in the meantime Facebook changed how peoples newsfeeds read further reducing the organic reach to 2% of their fans &fast company&. Based on this information suddenly the prospect of engaging with customers outside of the business through Facebook no longer seems that it is worth the time spent.

During the internship at Old West Escrow there hasn't been much improvment in the marketing department. Currently the focus of the conversations revolved around cutting expenses in order to use the money saved for other marketing plans. Our current outlook has revolved around possibly using social media as a means to engage in our customer base. At this time the though process is what segment should the company focus on. The company currently see three possible market segments as a source of new accounts. The markets are priviate sellers and buyer, real estate lawyers, and real estate agents. Since the nature of the companies business is obscure the best marketing practice should be marketing through education of the public. 

Education based marketing is the sharing of knowledge with teh purpose of building trust. When a company uses this strategy they are wanting to establish credibility with thier customers. Industries where this is the most effective is the finiacial services companies. & Forbes & notes that in the finiacial industries there is a gap between the consumer understanding and the professional. To fill this gap the company needs to educate through information and knowledge forgoing the traditional direct marketing methods. & Forbes & lists several topics to consider when devloping this approch. 1. Seek the answer to question the consumer is asking. 2. Identify consumer touch points including direct mail, websites, word of mouth, and publicity. 3. Develop a message that get a response. The company needs to speak to the consumers challenges, problems, and goals. 4. The company needs to add value at every opportunity. Customers want advice and knowledge without requiring anything in return & Forbes &.

Applying the education based marketing at Old West Escrow is impairative. While working with the company this approached jumped out because the most common misunderstanding is that the company is withholding thier money or documents. Looking at this from a prospective consumer the casts a shadow of untrustworthiness around the company scaring new clients to use the bank approach even though their pricing is higher.

**** Learning Outcome Three

The basic job of an account manager at Old West Escrow involves the daily processing of loan payments for the private party contracts. Old West Escrow does not own any of these loans they only act as a neutral third party to private transactions performing basic accounting functions such as applying intrest and principal to the accounts ledger. The process of learning this job was fairly straight forward only requiring simple addition, subtraction and multiplication. To perform this job function one only needs to enter the payment into the computer system and in most cases the system will perform the mathmatics correctly. Understanding the math part was also straight forward. The account manager needs to be able to multiply the principal balance by the interest rate then divide the result by the type of interest that is charged on the account. For new accounts manual method is used as means to perform a check on the computer ensuring the account if functioning correctly. 

The external factors when learning this job is learning how to work with the customers in a manner of being neutral in the process. Since this is the case the company cannont take the stance that the customer is always right. If they would work this way they would not be usefull in protecting both parties against each other. These conflicts are what I was most interested in learning about. As an escrow agent the agent needs to stand their ground and show proof why they are performing a function a certain way. During many encounters the most common misunderstanding was calulating interest. I have learned that regular customers don't understand interest calculated based on 365 days vs 360 days. Other misunderstandings are when customers don't realize thier payments were amoritized with thier payments not meeting the amount of interest charged on the account. Both of these topics put Old West Escrow in delicate situations since both parties feel that the company created the contracts on their accounts. A process in handling the customers that are having problems was to create a form letter that breaks down the math on their account step by step showing the entire process from start to finish. For most cases this process has worked with settleing the issues they have. Other issues that arises are when the contracts the company handles are conflicting with accounting practices or conflicting with other sections within the same contract. In these instances the company will not contact the parties because they will want what benifits them. In these cases Old West Escrow will contact the person who drew up the contract which will then clarify with an addendum. In any case when a companies purpose is to act as a neutral third party it's important them to act a mediators between the two. Without having the basic skills of conflict mediation this company would find it difficult perform the job they were hired for. 

**** Learning Outcome Four

From past knowledge to observed knowledge I understand that sometimes there is not enough hours in a day to perform the day to day activities that are required of a small business. In this learning objective I set out to observe what was required of the business owner. At this location the company is a bookkeeper for several trust accounts as well as their own accounts. This process alone is a vary tidius process of balancing the accounts as a daily activity considering thier volume of incoming and outgoing checks. Other activies involve keeping the employees tasked ensuring all account records are kept up to date, creating marketing materials, updateing forms, and updating the companies website. All the aforementioned are part of an everyday process sometimes resulting in some work being delayed for other more pressing work. This learning objective is not yet fully realized in the sense that we will know all the answers. What I have learned is that this will be a evolving process that will constantly change over time.

The process that is the most important is the managing of the several trust accounts that the company oversees. When a payment from a customer is recieved the company takes that payment then splits the payment where it needs to go. Parts of some payments are sent to a reserve account to be dispersed at a later date while other parts are split off as the fee the company collects as part of their income. The rest of the payment are then sent to the sellers of the contract as part of their proceeds. The time spent in this area is not the dispersments of the contract monies but after all payments are sent to thier perspective cashiers. Currently the software package the company uses does not allow for bank account reconcilation. The software only records the checkbook register. Using this information the goal is to understand the process and what part of the process could use improvement. From observations the process is balancing the checkbook. Since there are so many daily transactions compounded with the delays of the mail services and bank transaction delays the balancing process is a tidus process at best. 

Working with the owner of the company we tried several accounting software packages to help keep track of the companies trust accounting. There are some basic problems with consumer software such as Quickbooks and Sage Enterprise accounting software. They are not equiped to handle trust accounting. There were ways to set the software to make accounts as contra accounts but still lacked the functionality of showing the company how much they had outstanding in non-chashed checks. The next issue when using this software for trust accounting was finding the time daily to balance the accounts against checks and deposits that were recieved the day before. Currently there is one option that we haven't tried yet which is to simplify the process to simply showing daily credits and debits. When visiting with the owner this might be the best way to truley see the daily snapshot of the companies trust accounts.

Other issues of concern were generating new accounts. How is a business of this size going to devote the time and energy into reaching out to new perspective clients. Currently as mentioned in an earlier learning objective the company is using a passive approach to generating new business. The reason is because the company doesn't have enough capital to pay a firm to create marketing copies and between the owner and the employee they are not finding enough time to adaquatly generate new marketing material. For these reasons the company relies on the use of the Yellow Pages and word of mouth in order to generate new business. These same problems can be echoed across the entire small business community which is a reflection of how a small business stays a small business. Again the goal was to find ways to advertise the company without spending extra money and spending time that they don't have. The solution to this problem will continully evolve as their marketing plan changes. Some of the options that we talked about though were to stop the advertising in the Yellow Pages and use that money to hire a web design firm to design a website using search engine optimization to increase search results. The idea of releasing the Yellow Pages as a form of advertising came from a Marketing class that I took last year. The text in the class provided usefull information about the cost of entry for that medium. The cost is rather high when compaired to the amount of prospective customers actually use the product. When looking at this company, the company currently spends over $2,300 a year on a marketing product that they weren't sure genereated any business. 

The last part of the learning objective was observing how the company manages to employees and company while handling the other pressing matters on a daily basis. What I like about this objective is there is no right way to perform the daily functions. This SMB and other SMB's that are in the same professional offices perform organizaitonal functions as a similar process. These work groups function more as a colabrative teams than as a hierarchical structure. These companies perform as a latural team with each member performing job duties based on their strenghths assinging work to other members if they become overloaded. I find this really works speding up production in such work centers. In past expirences organizations will typically work as a top down organization where the managers assign their employees with work and each job is compartmentalized. My observations from observing this company along with others in the professional builing indicate that using such a system might not work as well because of their size. This observation indicates that working as a colabrative team may work better for companies if the employee size does not exceed the maximum chain of authority. 

**** Learning Outcome Five
**** Learning Outcome Six
  
*** Parallels to Program Study
*** Internship Improvments
*** Most Important Improvment
**** Personal Growth
**** Personal Strengths
**** Improvement to Academic and Career Goals
* Resume
* Journal Entries
** January 11-17


Job Description

Account Manager

My job at Old West Escrow is to record numerical data to keep financial records complete. This is done by performing any combination of routine calculating, posting and verifying duties to obtain primary financial data for the use to administer privately funded contracts. The job also requires the accuracy of figures, calculations, and postings pertaining to business transactions recorded by other workers. 

** January 18-24

My Organization is for this internship is Old West Escrow Company Inc. They are located at 2800 Jackson blvd in Rapid City South Dakota. This organization is very small and I would classify it as a micro business. There are not vary many employees considering that it doesn't take much work to complete the job. At this point in time the organization consists of the CEO/ Owner and one other employee. 

** January 25-30
				   
The effective and ineffective communications at this intern site are many. I feel the ineffective communication stems from generational gaps. The effective communication is awesome. The employees communicate with the owner freely and openly and the owner clearly verbally communicates with her employees asking for clarification when needed. The ineffective communication comes when technology is involved. The owner doesn't understand the use of email and will only use a fax machine when communicating with outside companies. On the other hand the other employee uses email to do this communicating. This prove to be vary ineffecient because depending on who answers the phone calls during the day coraspondance is performed differently with the outside companies. If for instance a customer only has email and does not have access to a fax machine that customer then has to wait until the other employee sends the email. Sometimes because of this disconjointed system communication gets lost between the two and the tasking gets lost. I feel that this is unfortanent because this might send a message that Old West Escrow is disorganized. 

The internal effective communication is great between the owner and the employees. Both parties are equally open and willing to communicate about future offerings as well working together to solve problems that arise from the daily work. One such incident where I noticed this was when there was a disagreement about how to apply a late charge on the account. The contract states to apply the late fees on a per day basis. The conflict happened when they made a payment and enoumous late fees kicked in. Both the owner and the employee were right on their thinking and instead of getting mad at each other they worked the problem out with math to make their case. There was collaboration between the two until they figured out the problem. I really liked this aspect because I have worked in so many organizations where employees thought and ideas don't ever seem to matter to the ones in charge. In the case of this organization both the employee and the management work together in a seamless environment making a frictionless environment. 

** February 1-7

Within the organization there is a divide in reguards to the technology that is used. When I arrived at the organization they were still using a dos made program that hasn't been updated since the mid 1990's. As we might guess this program has limitations when working in the technology driven world that we live in today. As mentioned earlier not all the employees work from email. The owner of the company doesn't ever want to use email for external communications while the rest of the world uses exactly that technology for those tasks.

In today's customer marketplace customers demand that everything they do to be connected by their fingertips. In my expirence when a customer is doing finicial transactions they want to be able to see those transactions when they want to. They don't want to call the company for every question they have. This is where using technology that was built for pre-internet doesn't work that well with maintaining customer relationships.

The main recomandation I have for this organization is to have all employees using the same technologies across the board. Having one person using aniquated technology only while the other is keeping more modern using email with attachments cause confusion between employees. This confusion then enables the organization to deliver delayed results because one maybe relying on the other to complete tasks. Personally I would like to see all employees embrace electronic communications in the future. The next item is the use of the software package that the company is using. With the software created in the mid-1990's there seems to be a lot that is left to be desired. When looking further into the type of software they use I found that there are in fact newer versions available that offer all the features that customers look for when dealing with financial transactions. I would recommend that the company undergo the software conversion process in order to take advantage possible gained competitive edge. 

** February 8-14

This internship is meeting all of my expectations thus far. When I picked this internship I wanted to better understand the challenges of running a small business. This organization is a small business with vary few employees. These types of businesses have their own set of challenges that the large companies don't seem to have or are easy hurdles to cross. I have worked at a number of large to mid-sized organizations and know the different red tapes they have to jump thorough. I have never been at such a company where budgets, human resources, capital huge restraints. Within these types of companies often times human resources and budgets go hand in hand. The organization truly needs more of the aforementioned ,however, the constraint mechnisums are such that without one the other cannot be performed. 

When looking at other companies that offer the same services this company would be classified as a mid-sized company. There are so few employees because it does not take an army of human resources to accomplish the daily work. It does however, need human capital that is highly versed in different aspects business management. What this means is that one person is responsible for the marketing, payroll, budgeting, and financial bookkeeping.  

** February 15-21

Since I chose to use an small business as my choice for my internship I feel that I am adaquately able to use most of the classroom learning from my undergraduate degree as well as my last three years with Chadron State University. So far I have been using areas from my marketing, public relations, accounting, math for managers etc. I feel that this is the most rounded expirence I could have come across. Throughout my time in this internship I am not just an inicent bystander during the process of the work week. My intern site has me working though the everyday problems and working directly with the customers. This site also values my input on best practices when looking at new competitive advantages. I am truly happy that during this adventure I have been able to use and practice all classroom teachings and apply them to real world examples. 

** February 22-29

There are many area's of this internship that I would like to share with my classmates that relates to to our classroom learning. The first expirance that I learned really quick was that during the internship when looking at market factors and finding the equalibriam it is not that simple. Finding what consumers are willing to pay verses their reactions to pricing seems to be more difficult to acheive. An example of this is when visiting with the company about new possible revenue streams on paper they seemed easy enough to accomplish. In practice when quoting the new different pricing the reactions varied greatly, sometimes over the smallest change that resulted in an extra dollar. At the same time when changing the pricing internally without a public notice the results seemed to be better taken of the consumer didn't know the price before hand. An example of this practice what changing the pricing of closing costs. Before the change the company was charging a flat rate for all closing but added on extra fees depending on how many payoff quotes had been requested. The new pricing changed out that variable and went with a flat fee plus a percentage cost basis. In this case consumers didn't think twice about the price charged. The origional way consumers would cry foul when tacking on extra fees because a external company requested payoff quotations at different times throughout the contrat to varify their credit worthiness. 

This example shows that finding the equalibrium in the market isn't simply the result of consumer surveys binded with the cost of goods or servies. Consumers are much more dynamic that this which can result in knee jerk reations. Though consumer surveying has it's place in our current market other external factors needs to take place to trulely find that market balance. 

** March 1-6

I have rather large long and short term career goals. Currently my short term career goals consists asking the question to myself of what can I do to make my job and internship better. Everyday I want to better the business that I work in. So my current short term goals consist of finding areas that needs improvment and finding ways to simplify the process that make work easier with the same amount of control and accracy as the current process. Currently I am working on a project to increase my companies revenue without raising costs. I am accomplishing this by sorting out unneeded expenses or expenses that are redundent. One area that I found was by chance. I was given the task of calling the phone company to order a new modem. This call resulted in learning that the comapany had not updated their service package since the year 2000. By ordering a new modem the company was switched to new updated packages that saved one hundred and thirty six dollars a month. This set me off to find other areas of similar interest. Another goal is to find ways to reduce the company's cost of postage. This is by far their largest expense for the year. Currently there are several options available to the company but the new processes also require an initial cost of entry before savings can happen. These short term goals are very short term but I choose these goals as my short term because they demonstrate the ability to problem solve. This is an important ablitiy that rolls into my larger long term goal.

My Long term goal is to own my own business. This is one reason that I chose a micro business as my intern site. If I would have chose a site where I was bounded to a certain department burried deep within a corperation I feel that would give me a vary narrow view of what the larger picture is. By choosing this type of site in a short time I am able to view the entire picture of what is needed when we look at professional and personnal skills.  In a the short time that I have had I have already learned that a SMB needs to have a well rounded understanding of all things business. They are the marketer, human resources, and accounting. Running this type is business is a trial and error process in many way. The process is also a never ending learning expirance. Of course the business can hire professional services to fill many of the gaps that exist, however, there is always the issue of cash flow that plagues each and every one of these companies. So by having this internship site I feel that I will be better poised to understand if my long term goals are attainable. 

** March 7-13

Being the type of company that Old West Escrow Company is everyday presents it's self with an ethical dilemma. The company acts as a neutral thrid party to private lending parties. A certain issue recently that arrose whs when an seller of a contract called us and said that he is closing the account and I need to send him all the money that was in the reserves account. The seller in this case feels that the money is his since he is foreclosing on his buyer and needs that money so he can pay the property taxes and insureance from here on out. However, this money is paid into a trust account by the buyers on the contract so at the company we felt that the money was rightfully the buyers money and he deserves to recieve that money back as a check in the event that the account is foreclosed on. In this situation I had to tell the seller that this is in fact not his money to withdraw when he wants and the money really belongs to the seller. The ethical considerations in this example maybe minor but could have enoumous implications if we would of released that money. In this case we chose to continue servicing the contract until we get legal defult instructions. 

The second ethical dilemma I want to talk about arose when I was doing a periodic check on accounting versus how the contract reads. In this example our company was following the contract exactly as it read in the contract. The issue we discovered is when we follow the amorization schedule exactly the buyer unknowingly ends up paying interest of principal that should have been reduced. What was happening is that the contract was so specific that each payment that we were to apply a certain amount to each principal and interest. What happens when we do this we discovered is that the buyer ends up paying interest on principal that should of been reduced because there would have been no more interest to deduct from his payment. Essintially this buyer had an large number of prepaid interest. The ethical dilemma comes from asking what are we supposed to do now that we have this information. We asked ourselves should we deduct the prepaid interest from the principal balance then continue forward following accounting practices or should we continue to service the contract as it was read. Both parties did sign accepting the terms and conditions of the contract. This issue currently is not resolved. However, the solution that we are taking is informing all parties to the contract including the lawer that wrote the contract that we are changing how interest is applyed because of the prepayment that happen as a result of processing according to the amoritization schedule. We arrived at this point because if we continue it would be impossible to figure when the contract has been fullfilled and have the seller repay the prepaid interest. 

** March 14-20

In my past organizations that I have worked for there have been many conflicts. Many of them stem from my personality I think. At first I come off as vary off standoffish or non-approchable. I personally feel that this should not be the case as I am really open minded. I do have issues though with having to prove that my ideas are the right way. In my prior organization I was a medic for a emergency mental health unit. As medics we considered ourselves as the medical athourity when it came to patient safety. There was no other medical advice that was available. In this particular incident a patient came in to be seen. They were not currently on any medications nor was there any signs of medically related trama. The one medical issue was that they were diabetic. The incident happened over night. The patients surgar levels rose dramaticly to very unsafe levels. The conflict was that the couslor currently working refused to release the patient because there theropy was not over yet, their reasoning was that the patient refuses to manage thier diabetes anyway so what harm will come from them not seeing the emergency room. At that point I was almost willing to walk out and quit my job. My thinking was what use is there having a medic on staff if other staff weren't going to listen to my medical advice. I don't think that this situation was ever fully resolved. From that point forward when I felt that a situation medically unsafe I would call the emergency room for medical advice. In these instances the medical doctor overrode what the counsolor was trying to perform and legally they could not keep the patient at the center. I eventually left that place of employment because it was becoming increasinly clear that medical advice from medics didn't hold weight and that model was no longer fitting into thier business plan.

** March 21-27

As I have previously mentioned in earlier journal entries there are a few items that would boost this organization forward. Albeit the moral is already vary high within the organiztion there are still several areas in which the organiztaion can make the daily work much easier to perform than the current routine. The first item is for the company to adopt the same practices for every employee when communicating. As I have mentioned the owner doesn't use email and will only use a fax machine to send documents various firms. If the outside firm doesn't use fax then they have to wait for another employee that uses email to scan their printed document and attach it as a email. This creates delays that are not needed. Once the organization starts to utilize emails as a official form of communication their effeciency greatly rises in this case. 

The second suggest is to update their software. The software company that currently supplies their software has updates that introduce many new features. All of the features are desighed with productivity in mind. The new software currently can handle automatic transactions from banks. Using this feature would currenly greatly reduce the time spent on daily processing but also reduce thier postage costs. Currently to enter these types of payments the company needs to creat batches in thier banking system to interface with the automated clearing house. Then once the batches are pulled they have to mannually enter each payment into thier daily processing. If using the new software once the automatic debit accounts were set up this process happens with just one button and all the payment are entered for the day. The same goes for the automatic credits. Currently the company is only sending checks by mail to the sellers bank accounts. By using the new software again the software saves a file that needs to be uploaded then all the sellers are paid without the need for extra postage costs. We have figured that not only would this simplify the processing of daily payment but would reduce the companies costs by over $5,000 a year. 

Thirdly by implimenting these changes the comapany can really start to focus on other aspects of the business such as securing new clients and increasing their advertising budgets. The down side is that the company needs to find the cash flow to purchase the new software. These are not cheap upgrades for a company of this size. If they find the money or financing for the new software I feel that it will pay for itself within the first year bringing in an extra $2,000 dollars after the the software expenses. 

** March 28-30

This internship has been so insightful throughout the past twelve weeks. For myself I have learning that even though I have been attending a graduate program I am by no means an expert in my field. Between working at my intern site and visiting with other business owners that are located in the same professional offices I still only have a sliver of the knowledge that is needed to be a successful business owner/operator. I know have great fundamentals that I was missing after attend my undergraduate school and this is a great base to work off of. Now what I need to do is put this knowledge to use in everyday practice. I need to create professional habbits that will endure for the long-run. I think the biggest lesson I learned for myself is when I have a goal it is important to take that goal in milestones. It is important to not move so fast as to lose the fundamentals along the way. I find it really easy to look at everthing from the stance that there is a problem and it needs to be fixed. In the future I will still hit the floor running but taking smaller steps taking the time to learn the entire process before finding the solution.

There is a weath of information that I learned from my employer. The company may be a small company but this by no means is a company with small knowledge. The company was founded in 1985 and since has filled a void in the market of home mortages. They show that buying property through a bank is not the only way to buy property or secure business loans. There is a weath of venture capitalist in the world that are willing to privatly fund a contract and many times proves to be more benificial to both parties. This is what I liked most. This company's heart is in the right place they want to show the world that we don't need to be bound by banks to fund large purchases such as land and houses. The other thing I learned is that it really important for a company such as this to hold items that act as collateral for the contract. In most cases for this company this results in documents such as warrenty deeds or titles. These item are important to their mission to keep documents safe until the contracts are fulfilled. Without these documents being held there is no incentive for either party to follow through until the end. 

When it comes to what I learned about my job. I learned that the mathmatical functions are the easy part. The hard part about this job is explaing to customers how to perform the math correctly. This is the biggest hurdle that I came across from day to day. The companies customers can't seem to ever figure out the difference between interest calculated on a 365 day basis or the 360 day basis interest. This confusion really starts some fights with the customer thinking the company applied the payments incorrectly. In sum what I learned from the job is how to handle these conflicts as they arise learning to break apart the math in simple steps that most people can understand. 
** April 4-10

This occupation or profession is a vary small subset of the current market. Generally speaking we won't see any company of this sort that is a large corperation. When talking with the owner of the company she explained to me that in the past years banks used to hold these types of transactions. What they quickly realized is that in order to service these transactions the bank would have to dedicate an person just for this process. These customers are more demanding and needs more attention then a bank would be willing to give without higher serviceing costs. So one by one they started selling these accounts to small escrow companies in the region because the small business is better equiped to handle these transactions. Currently there is still one bank in the region that handles escrow and untill recently accepted every type of escrow. In the recent months they are no longer accepting escrows of homes and private property and only accepting business to business transactions. I think this will start to be another area where the company will be able to pick up new accounts as there is still a demand for private property. Since it is not common for the large banks to handle these type of transactions the job outlook is small. The companies that are already formed have a good hold on the market. These companies are also not growing fast enough for them to expand and hire many employees. In the future I would like to stay with this company and grow with them. I truely feel they fill a need in the market but the challenge is finding ways to expand their accounts. This seems to be an uphill battle since the general public doesn't know that this is an option.  

* Thank You Letter
